# yamllint disable-line rule:line-length
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# yamllint disable-line rule:line-length
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
---
name: Content Validation

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        # yamllint disable-line rule:line-length
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        # yamllint disable-line rule:line-length
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          python -m pip install --upgrade pip
          pip install spectacles==2.3.0rc4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test Content Validation
        # yamllint disable-line rule:line-length
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        env:
          BRANCH: $(git rev-parse --symbolic --abbrev-ref HEAD)
        run: |
          spectacles content --base-url ${{ secrets.LOOKER_BASE_URL }} \
          --client-id ${{ secrets.LOOKER_CLIENTID }} \
          --client-secret ${{ secrets.LOOKER_CLIENTSECRET }} \
          --project ${{ secrets.PROJECT }}
