---
# yamllint disable-line rule:line-length
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# yamllint disable-line rule:line-length
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: LookML Validation

# yamllint disable-line rule:truthy
# yamllint disable-line rule:trailing-spaces, rule:truthy
on:
  workflow_call:
    inputs:
      BRANCH:
        required: false
        type: string
      AUTOMATION_PAT:
        required: false
        type: string
      LOOKER_BASE_URL:
        required: true
        type: string
      LOOKER_CLIENTID:
        required: true
        type: string
      LOOKER_CLIENTSECRET:
        required: true
        type: string
      PROJECT:
        required: true
        type: string
    secrets:
      AUTOMATION_PAT:
        required: false
      LOOKER_BASE_URL:
        required: true
      LOOKER_CLIENTID:
        required: true
      LOOKER_CLIENTSECRET:
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        # yamllint disable-line rule:line-length
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        # yamllint disable-line rule:line-length
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          python -m pip install --upgrade pip
          pip install spectacles==2.3.0rc4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test LookML Validation
        # yamllint disable-line rule:line-length
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        env:
          BRANCH: $(git rev-parse --symbolic --abbrev-ref HEAD)
          LOOKER_BASE_URL: ${{ secrets.LOOKER_BASE_URL }}
          LOOKER_CLIENTID: ${{ secrets.LOOKER_CLIENTID }}
          LOOKER_CLIENTSECRET: ${{ secrets.LOOKER_CLIENTSECRET }}
          PROJECT: ${{ secrets.PROJECT }}
        run: |
          spectacles lookml --base-url ${{ inputs.LOOKER_BASE_URL }} \
          --client-id ${{ inputs.LOOKER_CLIENTID }} \
          --client-secret ${{ inputs.LOOKER_CLIENTSECRET }} \
          --project ${{ inputs.PROJECT }}
